### ISSUE TITLE
Different header?

### ISSUE THREAD

**Issue by IeuanWalker** [JimiSmith/AspNetCore-Versioning-Example#1]
I love this implementation, but is there a way instead of appending the Version number to the accept header, create a new header just for the version. e.g.
Instead of this -
```
Accept: application/json;v=1.0
```
Do this -
```
Accept: application/json
Api-Version: 1.0
```

**Comment by JimiSmith** [comment]
Yeah. There's a range of options. Have a look here: https://github.com/Microsoft/aspnet-api-versioning/wiki/API-Version-Reader

**Comment by IeuanWalker** [comment]
@JimiSmith Great thanks.

So at the moment, I have done this -

```csharp
o.ApiVersionReader = ApiVersionReader.Combine(
    new HeaderApiVersionReader("Api-Version"), // Adds a new header for api versioning
    new MediaTypeApiVersionReader() // read the version number from the accept header
);
```
I have kept the `MediaTypeApiVersionReader `so that swagger can still auto version. How would i add new header for "Api-Version" that swagger can auto use.

**Comment by JimiSmith** [comment]
You should be able to add a Parameter to the operation in `ApiVersionOperationFilter` that describes the header. I think you just need to set the In property to 'header' and then set a name and a default value. I haven't tested it but it should work
